### ISSUE TITLE
[SUGESTÃO] Adicionar um "template" para novas sugestões de melhorias

### ISSUE THREAD

**Issue by igrfranca** [cervenyps/simple-bank-py#1]
Após iniciar uma nova issue, seria interessante o repositório disponibilizar campos pré-definidos para a abertura padronizada da sugestão ou bug.

Exemplo: 

Bug report [DEFEITO]
Informe o problema encontrado

Feature request [SUGESTÃO]
Informe a sugestão

**Comment by cervenyps** [comment]
Feito no commit 0fe4fd90c53926554974ca4d8718da7186d0eb66

Obrigado pela sugestão! :rocket:
